[package]
name = "lighting"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
colortemp = "0.1.0"
image = "0.25.9"
palette = { version = "0.7.6", features = ["std"] }
rayon = "1.11.0"
